import dotenv from 'dotenv';
import mongoose from 'mongoose';
import Pooja from '../models/Pooja.js';
import Priest from '../models/Priest.js';
import Muhurta from '../models/Muhurta.js';
import Temple from '../models/Temple.js';
import Blog from '../models/Blog.js';
import { connectDB } from '../config/db.js';

dotenv.config();

export const poojasSeed = [
  {
    name: 'Satyanarayan Pooja & Katha',
    slug: 'satyanarayan-pooja-katha',
    shortDescription: 'Complete traditional Satyanarayan Pooja performed by experienced Vedic priests for peace, prosperity and family well-being.',
    description: 'Lord Satyanarayan is an embodiment of truth and righteousness. Performing this pooja brings mental peace, financial stability, and divine harmony to the household.',
    duration: '2.5 - 3 hrs',
    price: 2500,
    rating: 4.9,
    reviewCount: 142,
    materials: ['Flowers', 'Kumkum', 'Turmeric', 'Bananas', 'Pure Ghee', 'Coconuts', 'Sweets'],
    occasion: 'Monthly / Housewarming / Birthday',
    categories: ['Vrat & Katha', 'Monthly Rituals'],
    cities: ['Bengaluru', 'Mumbai', 'Delhi NCR', 'Hyderabad'],
    priestRequirements: '2 Vedic Priests',
    image: '',
    isActive: true,
  },
  {
    name: 'Griha Pravesh & Vastu Shanti Havan',
    slug: 'griha-pravesh-vastu-shanti-havan',
    shortDescription: 'Auspicious housewarming ritual with Vastu Purusha pujan, Navagraha Havan, and Ganesh Pujan.',
    description: 'Sanctify your new home before moving in. Removes negative energy and invokes divine blessings of Lord Ganesha and Vastu Purusha.',
    duration: '3.5 - 4 hrs',
    price: 5100,
    rating: 4.95,
    reviewCount: 210,
    materials: ['Navadhanya', 'Havan Samagri', 'Mango Leaves', 'Kalash', 'Coconuts', 'Ghee'],
    occasion: 'New Home Entry',
    categories: ['Housewarming', 'Havan & Homam'],
    cities: ['Bengaluru', 'Mumbai', 'Delhi NCR', 'Hyderabad'],
    priestRequirements: '2 - 3 Vedic Priests',
    image: '',
    isActive: true,
  },
  {
    name: 'Maha Mrityunjaya Jaap & Havan',
    slug: 'maha-mrityunjaya-jaap-havan',
    shortDescription: 'Sacred Vedic chanting of Lord Shiva for health, longevity, protection and spiritual energy.',
    description: 'The Maha Mrityunjaya Mantra is one of the most powerful healing mantras from the Rigveda. Chanted 108 or 1008 times by certified Vedic pandits.',
    duration: '2 - 3 hrs',
    price: 3500,
    rating: 4.88,
    reviewCount: 95,
    materials: ['Bael Leaves', 'Milk', 'Honey', 'Havan Samagri', 'Ghee', 'Coconuts'],
    occasion: 'Recovery / Birthday / Protection',
    categories: ['Health & Protection', 'Shiva Worship'],
    cities: ['Bengaluru', 'Mumbai', 'Delhi NCR', 'Hyderabad'],
    priestRequirements: '2 Vedic Priests',
    image: '',
    isActive: true,
  },
  {
    name: 'Navagraha Shanti Havan',
    slug: 'navagraha-shanti-havan',
    shortDescription: 'Pacify planetary afflictions and invoke positive cosmic vibrations for all 9 celestial grahas.',
    description: 'Harmonize planetary influences in your horoscope. Recommended during Dasha transitions or planetary afflictions.',
    duration: '2.5 hrs',
    price: 3100,
    rating: 4.85,
    reviewCount: 78,
    materials: ['9 Grains', 'Colored Cloths', 'Navagraha Sticks', 'Ghee', 'Sweets'],
    occasion: 'Dosha Shanti / New Year',
    categories: ['Astrological Remedies', 'Havan & Homam'],
    cities: ['Bengaluru', 'Mumbai', 'Delhi NCR', 'Hyderabad'],
    priestRequirements: '1 - 2 Vedic Priests',
    image: '',
    isActive: true,
  },
  {
    name: 'Lakshmi Kuber Pooja & Havan',
    slug: 'lakshmi-kuber-pooja-havan',
    shortDescription: 'Invoke Goddess Lakshmi and Lord Kuber for business growth, financial abundance, and stability.',
    description: 'Ideal for Diwali, business inauguration, or financial growth. Includes Sri Suktam path and Kuber Yantra pujan.',
    duration: '2 hrs',
    price: 2800,
    rating: 4.92,
    reviewCount: 115,
    materials: ['Lotus Flowers', 'Silver Coins', 'Kumkum', 'Sweets', 'Ghee', 'Coconuts'],
    occasion: 'Diwali / Business Launch',
    categories: ['Wealth & Prosperity', 'Business'],
    cities: ['Bengaluru', 'Mumbai', 'Delhi NCR', 'Hyderabad'],
    priestRequirements: '1 Vedic Priest',
    image: '',
    isActive: true,
  },
  {
    name: 'Rudrabhishek Pooja',
    slug: 'rudrabhishek-pooja',
    shortDescription: 'Sacred bathing of Shiva Lingam with milk, honey, sugarcane juice, and Panchamrit accompanied by Rudram chanting.',
    description: 'A deeply reverent ritual dedicated to Lord Shiva to burn past karma, bring emotional calm, and fulfill noble desires.',
    duration: '2 hrs',
    price: 2700,
    rating: 4.96,
    reviewCount: 168,
    materials: ['Panchamrit', 'Milk', 'Honey', 'Sugarcane Juice', 'Bael Leaves', 'Flowers'],
    occasion: 'Maha Shivratri / Mondays',
    categories: ['Shiva Worship', 'Abhishekam'],
    cities: ['Bengaluru', 'Mumbai', 'Delhi NCR', 'Hyderabad'],
    priestRequirements: '1 - 2 Vedic Priests',
    image: '',
    isActive: true,
  },
];

export const priestsSeed = [
  {
    name: 'Pt. Ramesh Sharma',
    email: 'ramesh.sharma@example.com',
    phone: '+919876543210',
    photo: '',
    experience: '15+ yrs exp',
    languages: ['Sanskrit', 'Hindi', 'Kannada'],
    specializations: 'Griha Pravesh & Mahamrityunjay',
    city: 'Bengaluru',
    serviceAreas: ['Indiranagar', 'Koramangala', 'Jayanagar', 'Whitefield'],
    templeAssociation: 'Sringeri Mutt Certified',
    biography: 'Dedicated Vedic priest with over 15 years of experience conducting authentic rituals across South and West India.',
    rating: 4.95,
    reviewCount: 98,
    startingPrice: 2100,
    availability: true,
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    name: 'Pt. Ananthakrishna Shastri',
    email: 'anantha.shastri@example.com',
    phone: '+919876543211',
    photo: '',
    experience: '18+ yrs exp',
    languages: ['Sanskrit', 'Kannada', 'English', 'Telugu'],
    specializations: 'Navagraha Havan & Vastu Shanti',
    city: 'Bengaluru',
    serviceAreas: ['Indiranagar', 'Malleswaram', 'Rajajinagar', 'HSR Layout'],
    templeAssociation: 'Sringeri Sharada Peetham',
    biography: 'Renowned scholar specializing in Vastu Shanti, Griha Pravesh, and complex Shanti Havans with precise pronunciation.',
    rating: 4.98,
    reviewCount: 184,
    startingPrice: 3100,
    availability: true,
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    name: 'Pt. Vasudev Acharya',
    email: 'vasudev.acharya@example.com',
    phone: '+919876543212',
    photo: '',
    experience: '12+ yrs exp',
    languages: ['Sanskrit', 'Hindi', 'Marathi'],
    specializations: 'Satyanarayan Katha & Lakshmi Pooja',
    city: 'Mumbai',
    serviceAreas: ['Dadar', 'Andheri', 'Bandra', 'Thane'],
    templeAssociation: 'Kashi Vidwat Parishad',
    biography: 'Experienced Acharya performing home poojas, company inaugurations, and monthly Satyanarayan Kathas.',
    rating: 4.89,
    reviewCount: 76,
    startingPrice: 2500,
    availability: true,
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    name: 'Pt. Sudarshan Bhat',
    email: 'sudarshan.bhat@example.com',
    phone: '+919876543213',
    photo: '',
    experience: '20+ yrs exp',
    languages: ['Sanskrit', 'Kannada', 'Tamil'],
    specializations: 'Rudrabhishek & Vivaha Sanskar',
    city: 'Bengaluru',
    serviceAreas: ['Jayanagar', 'JP Nagar', 'Banashankari', 'Basavanagudi'],
    templeAssociation: 'Krishna Yajurveda Ghanapathi',
    biography: 'Ghanapathi priest known for flawless Vedic mantra chanting and traditional family samskaras.',
    rating: 4.97,
    reviewCount: 220,
    startingPrice: 3500,
    availability: true,
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    name: 'Pt. Venkatesh Dixit',
    email: 'venkatesh.dixit@example.com',
    phone: '+919876543214',
    photo: '',
    experience: '14+ yrs exp',
    languages: ['Sanskrit', 'Hindi', 'English'],
    specializations: 'Kuber Pooja & Office Inauguration',
    city: 'Delhi NCR',
    serviceAreas: ['Gurugram', 'Noida', 'South Delhi', 'Dwarka'],
    templeAssociation: 'Shukla Yajurveda Ratna',
    biography: 'Specialized in corporate and residential poojas, Vastu remedies, and planetary peace rituals.',
    rating: 4.91,
    reviewCount: 112,
    startingPrice: 2800,
    availability: true,
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    name: 'Pt. Rajesh Namboodiri',
    email: 'rajesh.namboodiri@example.com',
    phone: '+919876543215',
    photo: '',
    experience: '16+ yrs exp',
    languages: ['Sanskrit', 'Malayalam', 'English', 'Tamil'],
    specializations: 'Ganapathi Havan & Bhagavathy Seva',
    city: 'Hyderabad',
    serviceAreas: ['Banjara Hills', 'Jubilee Hills', 'Gachibowli', 'Secunderabad'],
    templeAssociation: 'Kerala Samskrita Peetam',
    biography: 'Expert in Kerala tantrik traditions, Ganapathi Havan, and protection rituals for peace and harmony.',
    rating: 4.93,
    reviewCount: 89,
    startingPrice: 2700,
    availability: true,
    verificationStatus: 'APPROVED',
    isActive: true,
  },
];

export const muhurtasSeed = [
  {
    date: new Date('2026-09-12T06:15:00Z'),
    type: 'GRUHA_PRAVESH',
    title: 'Griha Pravesh (Housewarming)',
    description: 'Highly auspicious for moving into a new home or starting major renovation work. Invokes Vastu Purusha blessings.',
    tithi: 'Shukla Paksha Ekadashi',
    nakshatra: 'Uttara Phalguni',
    rahuKalam: '09:00 AM - 10:30 AM',
    abhijitMuhurta: '11:45 AM - 12:30 PM',
    location: 'Bengaluru',
    source: 'Development Sample Panchang',
    isActive: true,
  },
  {
    date: new Date('2026-10-04T07:30:00Z'),
    type: 'WEDDING',
    title: 'Marriage (Vivaha Sanskar)',
    description: 'Excellent planetary alignment for sacred matrimonial unions and auspicious family gatherings.',
    tithi: 'Shukla Paksha Dwitiya',
    nakshatra: 'Rohini',
    rahuKalam: '04:30 PM - 06:00 PM',
    abhijitMuhurta: '11:50 AM - 12:35 PM',
    location: 'General',
    source: 'Development Sample Panchang',
    isActive: true,
  },
  {
    date: new Date('2026-09-18T08:45:00Z'),
    type: 'NAMING_CEREMONY',
    title: 'Namakarana (Naming Ceremony)',
    description: 'Favorable planetary combination for whispering the newborn’s sacred name and conducting Sun worship.',
    tithi: 'Shukla Paksha Saptami',
    nakshatra: 'Anuradha',
    rahuKalam: '10:30 AM - 12:00 PM',
    abhijitMuhurta: '11:40 AM - 12:25 PM',
    location: 'General',
    source: 'Development Sample Panchang',
    isActive: true,
  },
  {
    date: new Date('2026-09-25T09:15:00Z'),
    type: 'BUSINESS',
    title: 'Business & Office Launch',
    description: 'Pushya Nakshatra on Purnima ensures financial stability, customer growth, and long-term business prosperity.',
    tithi: 'Shukla Paksha Purnima',
    nakshatra: 'Pushya',
    rahuKalam: '10:30 AM - 12:00 PM',
    abhijitMuhurta: '11:42 AM - 12:28 PM',
    location: 'General',
    source: 'Development Sample Panchang',
    isActive: true,
  },
];

export const templesSeed = [
  {
    name: 'Kashi Vishwanath Temple',
    slug: 'kashi-vishwanath-temple',
    description: 'One of the holiest Hindu temples dedicated to Lord Shiva, located on the western bank of the sacred Ganges River.',
    deity: 'Lord Shiva (Jyotirlinga)',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    country: 'India',
    address: 'Lahori Tola, Varanasi, Uttar Pradesh 221001',
    category: 'Jyotirlinga',
    images: [],
    website: 'https://shrikashivishwanath.org',
    timings: '03:00 AM - 11:00 PM',
    isActive: true,
  },
  {
    name: 'Tirumala Venkateswara Temple',
    slug: 'tirumala-venkateswara-temple',
    description: 'World-renowned hilltop temple dedicated to Lord Venkateswara, an incarnation of Vishnu who resides to preserve dharma.',
    deity: 'Lord Venkateswara (Vishnu)',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    country: 'India',
    address: 'Tirumala, Tirupati, Andhra Pradesh 517504',
    category: 'Divya Desam',
    images: [],
    website: 'https://tirupatibalaji.ap.gov.in',
    timings: '03:00 AM - 11:30 PM',
    isActive: true,
  },
  {
    name: 'Siddhivinayak Temple',
    slug: 'siddhivinayak-temple',
    description: 'Revered temple in Prabhadevi, Mumbai, dedicated to Lord Siddhivinayak, the granter of wishes and remover of obstacles.',
    deity: 'Lord Ganesha',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    address: 'SK Bole Marg, Prabhadevi, Mumbai, Maharashtra 400028',
    category: 'Ganesh Kshetra',
    images: [],
    website: 'https://siddhivinayak.org',
    timings: '05:30 AM - 10:00 PM',
    isActive: true,
  },
  {
    name: 'Somnath Temple',
    slug: 'somnath-temple',
    description: 'The first among the twelve holy Jyotirlinga shrines of Lord Shiva, standing gracefully by the Arabian Sea.',
    deity: 'Lord Shiva (First Jyotirlinga)',
    city: 'Prabhas Patan',
    state: 'Gujarat',
    country: 'India',
    address: 'Somnath Mandir Rd, Veraval, Gujarat 362268',
    category: 'Jyotirlinga',
    images: [],
    website: 'https://somnath.org',
    timings: '06:00 AM - 09:30 PM',
    isActive: true,
  },
];

export const blogsSeed = [
  {
    title: 'Complete Guide to Griha Pravesh Pooja: Rituals, Muhurta & Checklist',
    slug: 'complete-guide-to-griha-pravesh-pooja',
    excerpt: 'Step-by-step Vedic guide on preparing for your housewarming ceremony, auspicious items required, Vastu Purusha pujan, and sacred mantras.',
    content: 'Sanctifying your new home with Griha Pravesh brings divine vibrations and removes negative energetic residuals...',
    category: 'Pooja Guides',
    author: 'Vedic Heritage Editorial',
    publishedAt: new Date('2026-08-14'),
    isPublished: true,
  },
  {
    title: 'Understanding Panchang: How Auspicious Muhurtas Are Calculated',
    slug: 'understanding-panchang-how-auspicious-muhurtas-are-calculated',
    excerpt: 'Demystifying Tithi, Vara, Nakshatra, Yoga, and Karana. Learn how Vedic astrology determines optimal timing for life decisions.',
    content: 'The Vedic Panchang is a sophisticated astronomical calendar measuring five essential elements of time...',
    category: 'Vedic Knowledge',
    author: 'Panchang Research Group',
    publishedAt: new Date('2026-08-08'),
    isPublished: true,
  },
  {
    title: 'Significance of Satyanarayan Katha: Benefits of Monthly Observance',
    slug: 'significance-of-satyanarayan-katha',
    excerpt: 'Discover the ancient Puranic origins of Sri Satyanarayan Pooja, its spiritual symbolism of truth, and why millions observe this monthly Vrat.',
    content: 'Lord Satyanarayan represents the supreme truth. Observing monthly Satyanarayan Katha invokes mental calm and family harmony...',
    category: 'Spiritual Practices',
    author: 'Vedic Heritage Editorial',
    publishedAt: new Date('2026-07-28'),
    isPublished: true,
  },
];

export const seedDatabase = async () => {
  console.log('Populating Mongoose database collections with seed data...');
  await Promise.all([
    Pooja.deleteMany({}),
    Priest.deleteMany({}),
    Muhurta.deleteMany({}),
    Temple.deleteMany({}),
    Blog.deleteMany({}),
  ]);

  await Pooja.insertMany(poojasSeed);
  await Priest.insertMany(priestsSeed);
  await Muhurta.insertMany(muhurtasSeed);
  await Temple.insertMany(templesSeed);
  await Blog.insertMany(blogsSeed);
  console.log('Mongoose database collections seeded successfully!');
};

const runSeedScript = async () => {
  try {
    await connectDB();
    await seedDatabase();
    process.exit(0);
  } catch (error) {
    console.error(`Database seeding failed: ${error.message}`);
    process.exit(1);
  }
};

if (import.meta.url === `file://${process.argv[1]}`) {
  runSeedScript();
}
